version: '3'
services:
  qexo:
    image: homuras/qexo-docker:latest
    container_name: qexo
    environment:
      #- ACMEMAIL= xxx@qq.com  #申请证书用
      - QEXODOMAIN=blog.example.com
      - IP=192.168.5.4      #区域网ip
      #- HEXODOMAIN=            #不填不反代hexo 填了会申请证书

    volumes:
      - /path/to/Qexo:/usr/local/qexo
      - /path/to/hexo:/path/to/hexo
    ports:
      - "8000:8000"
  hexo:
    image: homuras/hexo-docker:latest
    container_name: hexo
    ports:
     - "4000:4000"
    volumes:
     -/path/to/hexo:/hexoFomalhaut   #注意与qexo的hexo路径相同
